### ISSUE TITLE
Some small caps have serifs

### ISSUE THREAD

**Issue by efherrera** [burnnat/capitals#3]
I have noticed that the f and the s in all my words are small capped with serifs.  Is this a known issue?  Is there a way to fix this.  I can use the small s for certain words, but can't do the same with the f.

**Comment by burnnat** [comment]
Fixed as of [Release 5](https://github.com/burnnat/capitals/releases/tag/v5). Now defaults to a new "scaled" rendering method, which will work for fonts without higher-order unicode characters included.
